### PR TITLE
Add DockerHost class

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
This moves this class https://github.com/spotify/helios/blob/master/helios-testing/src/main/java/com/spotify/helios/testing/DockerHost.java#L18 and this class https://github.com/spotify/helios/blob/master/helios-services/src/main/java/com/spotify/helios/servicescommon/DockerHost.java#L29 from Helios to docker-client.

**Comment by davidxia** [comment]
@mattnworb @gimaker @rohansingh

**Comment by mattnworb** [comment]
lgtm

**Comment by davidxia** [comment]
Tests passed but I canceled because I used rebuild with ssh.

**Pull request merged**
