### PR TITLE
Adding getters on Container.PortMapping

### PR DESCRIPTION
**Pull request by xcoulon**
Adding getters on the Container.PortMapping attributes. This is particularly interesting when clients need to consume the Port Mappings. In the current code, the only mean to extract the IP address, private/public ports and type are by parsing the result of the call to the Container.PortMapping#toString() method, which is a bit of a hack (and maybe not reliable in the long term) :-/

### CODE REVIEW

**Comment by rohansingh** [comment]
Are you sure you need to consume the port mappings, and not the realized bindings for a running container? See #41 for example.

**Comment by xcoulon** [comment]
@rohansingh 

Thanks for your reply. In our tooling, we want to display the list of all containers in table, in a similar fashion to what a user sees when he runs the 'docker ps -a' command.
Amongst all the containers I have on my docker host, one of them as for example the following port bindings (as retrieved via the 'docker inspect' command):
"Ports": {
            "27017/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "27017"
                }
            ]
        }  

But this is similar to what the PortMapping will give me when calling the Client#listContainers() method: PortMapping{privatePort=27017, publicPort=27017, type=tcp, ip=0.0.0.0}
Furthermore, I would prefer not having to send 'n + 1' queries to retrieve the list of containers and then inspect each one of them.

Am I missing something else ?
Thanks !

**Comment by rohansingh** [comment]
Makes sense. Would you mind fixing the spacing to match our conventions and the rest of the file (Google Java code style) & squash? I'll go ahead and merge it.

**Comment by xcoulon** [comment]
@rohansingh,
great ! I fixed the spacing in all the body of all the method I added and I rebased my branch. 
Sorry, I did not realize the initial additions did not match the coding convention :-/

**Comment by xcoulon** [comment]
thanks, @rohansingh !

**Comment by rohansingh** [comment]
@xcoulon Sure thing. Thank you for the contribution!

**Pull request merged**
