### PR TITLE
Upgrade jersey to upgrade dropwizard in helios

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by rohansingh** [comment]
:+1:

**Comment by davidxia** [comment]
:-1: Doing this makes helios not compile :(

**Comment by davidxia** [comment]
OK, got past that but now helios tests that talk to docker time out:

```
Running com.spotify.helios.system.JobExpirationTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 72.428 sec <<< FAILURE! - in com.spotify.helios.system.JobCreateTest
testInvalidHostname(com.spotify.helios.system.JobCreateTest)  Time elapsed: 71.361 sec  <<< ERROR!
java.util.concurrent.TimeoutException: null
	at com.spotify.helios.Polling.await(Polling.java:44)
	at com.spotify.helios.system.SystemTestBase.waitForMasterToConnectToZK(SystemTestBase.java:582)
	at com.spotify.helios.system.SystemTestBase.startDefaultMaster(SystemTestBase.java:562)
	at com.spotify.helios.system.SystemTestBase.startDefaultMaster(SystemTestBase.java:551)
	at com.spotify.helios.system.JobCreateTest.testInvalidHostname(JobCreateTest.java:37)
```

**Comment by rgrunber** [comment]
Just curious, is this change still planned, or has it been abandoned ?

**Pull request closed without merging**
