### PR TITLE
Add "pidsLimit" to HostConfig

### PR DESCRIPTION
**Pull request by CGNonofr**
Introduced in Docker api 1.11

### CODE REVIEW

**Comment by CGNonofr** [comment]
Do i have to make a unit test considering that this will only work with docker api >= 1.11 ?

**Comment by davidxia** [comment]
@CGNonofr Thanks for your PR. Yes, please add a test.

**Comment by CGNonofr** [comment]
I made a test and I don't understand why the build failed.
- for docker 1.10.3 the issue doesn't seem to be related to my pull request
- for docker 1.12.1 the test fails, but I don't know why nor how to fix it since it works on the same docker version on my computer!

**Comment by CGNonofr** [comment]
According to the documentation (https://docs.docker.com/engine/reference/commandline/create/), pidsLimit only works with a kernel >= 4.3, i think this is the issue!
What can we do?

**Comment by davidxia** [comment]
@CGNonofr You're right. Travis CI has kernel "Linux testing-gce-afb0b56d-a60a-4bf3-8b8d-bae07747d4c5 3.19.0-66-generic #74~14.04.1-Ubuntu SMP Tue Jul 19 19:56:11 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux". I've added to your PR here https://github.com/spotify/docker-client/pull/537.

**Pull request closed without merging**
