### PR TITLE
Added since and tail management to logs flow

### PR DESCRIPTION
**Pull request by damianopezzotti**
This modification allows to retrieve logs starting from a certain date or the last N rows

### CODE REVIEW

**Comment by davidxia** [comment]
@damianopezzotti Ah someone's already got a PR here for this https://github.com/spotify/docker-client/pull/221

**Comment by damianopezzotti** [comment]
Ok, but it has never been integrated in the master... Any chance to see
this functionality?

Il mercoledì 4 novembre 2015, David Xia <notifications@github.com> ha
scritto:

> @damianopezzotti <https://github.com/damianopezzotti> Ah someone's
> already got a PR here for this #221
> <https://github.com/spotify/docker-client/pull/221>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/pull/260#issuecomment-153837969>
> .
>


-- 
Damiano Pezzotti
...................................... . .
Software Architect | Alambitco
mobile +39 333 2116258
fax +39 02 700432209
email damy@alambitco.com
web www.alambitco.com
flickr www.flickr.com/photos/damianopezzotti
linkedin www.linkedin.com/in/damianopezzotti
pgp id 0x12DFD989

**Comment by davidxia** [comment]
@damianopezzotti I'm reviewing it now and will try to merge it soon.

**Comment by damianopezzotti** [comment]
My pull request or 221?

Il mercoledì 4 novembre 2015, David Xia <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha scritto:

> @damianopezzotti <https://github.com/damianopezzotti> I'm reviewing it
> now and will try to merge it soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/pull/260#issuecomment-153841199>
> .
>


-- 
Damiano Pezzotti
...................................... . .
Software Architect | Alambitco
mobile +39 333 2116258
fax +39 02 700432209
email damy@alambitco.com
web www.alambitco.com
flickr www.flickr.com/photos/damianopezzotti
linkedin www.linkedin.com/in/damianopezzotti
pgp id 0x12DFD989

**Comment by davidxia** [comment]
I'm reviewing #221 as the design there is more consistent with the original DockerClient interface.

**Pull request closed without merging**
