### PR TITLE
Support security options for container creation

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by dflemstr** [comment]
:+1:

**Comment by gimaker** [comment]
Does this work? The "POST /containers/create" endpoint [1] doesn't seem to accept an AppArmorProfile field -- only a SecurityOpts field.

[1]: https://docs.docker.com/reference/api/docker_remote_api_v1.18/

**Comment by davidxia** [comment]
@gimaker Good catch. I removed the apparmor stuff.

**Comment by gimaker** [comment]
https://docs.docker.com/reference/api/docker_remote_api_v1.18/ says this:

```
POST /containers/create
...
 "SecurityOpts": [""],
...
```

Note the 's' at the end of SecurityOpts (compared to the SecurityOpt in this PR).

Did you manage to test this out?

**Comment by gimaker** [comment]
:+1:

**Pull request merged**
