### PR TITLE
maven-shade-plugin 3.1.1

### PR DESCRIPTION
**Pull request by sullis**
latest version of the plugin

### CODE REVIEW

**Comment by sullis** [comment]
background:  
https://blogs.apache.org/maven/entry/apache-maven-shade-plugin-version

**Comment by sullis** [comment]
ready for review @mattnworb

**Comment by davidxia** [comment]
@sullis Thanks for the PR. Just curious, is there a particular fix or feature in the newer version that you need?

**Comment by sullis** [comment]
release notes for version 3.1.1:

https://blogs.apache.org/maven/entry/apache-maven-shade-plugin-version

Version 3.1.1 fixes bug "Maven Shade Plugin does not work under Java 10"

**Pull request merged**
