### PR TITLE
Added listExitedContainers() method

### PR DESCRIPTION
**Pull request by zanella**

### CODE REVIEW

**Comment by zanella** [comment]
#177

**Comment by davidxia** [comment]
@zanella Thanks for this. Maybe instead of its own special method, we can add another static method to `class ListContainersParam` that will generate the key and value?

**Comment by zanella** [comment]
@davidxia Absolutely, the "problem" is that the filter depends on "all=1", so I would have to return an Array/List<ListContainersParam>... am I wrong in my assumption ?

**Comment by davidxia** [comment]
@zanella Hm it seems to work without the all. See https://github.com/spotify/docker-client/pull/181

**Comment by zanella** [comment]
@davidxia Ah!, indeed, then #181

**Pull request closed without merging**
