### PR TITLE
Fixes #648 Use lowercase identitytoken

### LINKED ISSUE #648: identityToken RegistryAuth should look for identitytoken
## Description

My previous feature add #581 missed the mark slightly. I apparently goofed the actual identitytoken being entirely lowercase in my unit tests and code.

## How to reproduce

`RegistryAuth.fromDockerConfig()` with a real identitytoken based config.json file.

## What do you expect

RegistryAuth should be valid and correctly parsed.

## What happened instead

"Failed to parse auth string for {}"

## Software:

- `docker version`: 
```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```
- Spotify's docker-client version: 8.0.0

### PR DESCRIPTION
**Pull request by scheerer**

### CODE REVIEW

**Comment by scheerer** [comment]
Please hold on this... I am still verifying some things through the `docker-maven-plugin`. I'm having trouble getting it to find images that work through a normal `docker pull`. It doesn't seem to complain about authorization anymore though.

**Comment by davidxia** [comment]
Any way we can write a test for this?

**Comment by davidxia** [comment]
@scheerer Have you had a chance to verify things and/or write a test?

**Comment by scheerer** [comment]
Looks like there are more problems than I originally thought. There appears to be more to the identitytoken based auth than I care to dive into. :( Lets reject this for now

**Pull request closed without merging**
