### PR TITLE
Pull, push, build and create interruption

### PR DESCRIPTION
**Pull request by CGNonofr**
The Docker engine allows the client to cancel these requests by dropping the connection. (see https://docs.docker.com/engine/api/v1.25/)

### CODE REVIEW

**Comment by CGNonofr** [comment]
All tests are green!

**Comment by fraisse** [comment]
It should be really nice to have this functionnality

**Comment by nantoniazzi** [comment]
+1

**Comment by rtfpessoa** [comment]
Any reason for this not enter?

If the problem is just the merge conflicts, I would gladly fix them.

**Comment by CGNonofr** [comment]
Rebased!

**Comment by davidxia** [comment]
Upgrading jnr has been merged into master. If you rebase (sorry for making you do this again), the diff should be smaller.

**Comment by davidxia** [comment]
replaced by https://github.com/spotify/docker-client/pull/929

**Pull request closed without merging**
