### PR TITLE
use registryUrl in push command

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by mattnworb** [comment]
no test? :smile:

**Comment by davidxia** [comment]
@mattnworb Got some here now https://github.com/spotify/docker-client/pull/265

**Comment by davidxia** [comment]
But I can't really test that pushes to private registries work without setting up a publicly available private registry. The test in #265 checks that authed pushes to docker hub work.

**Comment by davidxia** [comment]
Let me know if you have good ideas :)

**Pull request merged**
