### PR TITLE
Attach stdout and stderr as streams to LogStream

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
Looking for a way to get the `stderr` and `stdout` streams from a running (attach) or stopped (logs) container as `InputStream`, I eventually came up with the following solution. I added a method `attach(outputstream, outputstream)` to `LogStream`, which then iterates over all incoming `LogMessages` and sends them to the correct stream. I'd like to hear your thoughts on this approach.

This can be used in the following ways:

### Binding to System.err and System.out
```java
dockerClient
  .logs(containerId, LogsParameter.FOLLOW, LogsParameter.STDERR, LogsParameter.STDOUT)
  .attach(System.out, System.err);
```

### Binding to piped inputstreams
```java
final PipedInputStream stdout = new PipedInputStream();
final PipedInputStream stderr = new PipedInputStream();
final PipedOutputStream stdout_pipe = new PipedOutputStream(stdout);
final PipedOutputStream stderr_pipe = new PipedOutputStream(stderr);

executor.submit(new Callable<Void>() {

  @Override
  public Void call() throws Exception {
    dockerClient
      .logs(containerId, LogsParameter.FOLLOW, LogsParameter.STDERR, LogsParameter.STDOUT)
      .attach(stdout_pipe, stderr_pipe);
    return null;
  }
  
});

try (Scanner sc_stdout = new Scanner(stdout);
    Scanner sc_stderr = new Scanner(stderr)) {
  assertThat(sc_stdout.next(), equalTo("stdout"));
  assertThat(sc_stderr.next(), equalTo("stderr"));
}
```

### CODE REVIEW

**Comment by rohansingh** [comment]
@JWGmeligMeyling Apologies for the delay on this. Reviewing it now.

**Comment by majst01** [comment]
Hi,

any chance to get this merged, i really like this feature.
Greetings

**Comment by rohansingh** [comment]
Merged now!

@JWGmeligMeyling Thanks for the great contribution with detailed comments!

**Comment by JWGmeligMeyling** [comment]
:smile:

**Comment by majst01** [comment]
:+1:

**Comment by walteryoung** [comment]
Hi,

Does this code still function? I can't find references to LogsParameter anywhere else.

I would like to get the StdOut from a container as a stream. Thanks!

dockerClient
  .logs(containerId, LogsParameter.FOLLOW, LogsParameter.STDERR, LogsParameter.STDOUT)
  .attach(System.out, System.err);

**Pull request merged**
