### PR TITLE
Update ContainerStats

### PR DESCRIPTION
**Pull request by johnflavin**
Addresses #402: Adds "blkio_stats" message as BlockIoStats class
Addresses #403: Adds "networks" message as ImmutableMap<String, NetworkStats>

### CODE REVIEW

**Comment by davidxia** [comment]
Oh, thanks for fixing my commit and making it an ImmutableMap.

**Comment by johnflavin** [comment]
I thought it would be good to cherry-pick your commit at the base of this branch, so if you rebase on this later git can hopefully figure out it doesn't need to duplicate that.

**Comment by johnflavin** [comment]
What's up with Travis? [The build for this PR](https://travis-ci.org/spotify/docker-client/builds/119809689) is just sitting around queued, as is [the build for the big testing update](https://travis-ci.org/spotify/docker-client/builds/119805138) merge into master.

**Comment by davidxia** [comment]
I had the same question the other day. @mattnworb told me he thinks it's
queued behind other travis builds for other arbitrary projects.

On Thu, Mar 31, 2016 at 10:40 AM, Flavin <notifications@github.com> wrote:

> What's up with Travis? The build for this PR
> <https://travis-ci.org/spotify/docker-client/builds/119809689> is just
> sitting around queued, as is the build for the big testing update
> <https://travis-ci.org/spotify/docker-client/builds/119805138> merge into
> master.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/pull/404#issuecomment-203969188>
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by mattnworb** [comment]
the fact that we launch so many builds in the matrix probably doesn't help either. Perhaps we don't need to test with the different DOCKER_HOST values any more and could remove 50% of them by removing that.

**Comment by davidxia** [comment]
Yea, is there a reason to test both unix and tcp?

On Thu, Mar 31, 2016 at 4:21 PM, Matt Brown <notifications@github.com>
wrote:

> the fact that we launch so many builds in the matrix probably doesn't help
> either. Perhaps we don't need to test with the different DOCKER_HOST values
> any more and could remove 50% of them by removing that.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/spotify/docker-client/pull/404#issuecomment-204108283>
>



-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by johnflavin** [comment]
This PR is good to go, ready for review. 

I'll preemptively point out something that I don't like but had to struggle with to get right: all the properties in `BlockIoStats` are `ImmutableList<Object>`. I couldn't figure out a better, more specific, type for them. The docker documentation for these properties is sparse. In my local testing, I could never get `stats` to return anything for any of those properties other than `null` or `[]`. I initially thought they'd be `String`s, but Jackson complained. Then I thought they would be `List<String>`s, but Jackson complained again. So I don't know what to expect there.

**Comment by johnflavin** [comment]
Another thought about Travis: when you guys are working in branches on spotify/docker-client, and you are keeping open a PR to merge that branch, both the branch and the PR trigger full builds every time you push a new commit. So that doubles the CPU time spent on each commit, along with doubling from testing both `unix://` and `tcp://`.

And what's more, Travis doesn't stop or cancel a build if a newer commit is pushed that obsoletes a previous commit. So sometimes builds are queued, taking a spot in line, but no one even wants them or cares about the result.

**Comment by mattnworb** [comment]
@johnflavin good point, I was curious about the separate settings for push and pr. Do you think it would make more sense to just have the build on `pr`, assuming that will trigger a new build if a PR is open and a commit is added to it? I was a little confused when setting that up so any experience/advice you have on Travis would be appreciated! :smile:

**Comment by davidxia** [comment]
I was confused by why there are two builds as well, ie push vs pr. The push build occurs for each new commit on that branch. The PR build isn't the same. It tests that the result of the merge commit from the PR onto master will pass.

So it seems good to have both.

**Comment by mattnworb** [comment]
I updated the Travis config to turn off "build on push" to see if that helps reduce the wait time. I don't think that we are often pushing branches to this repo where we don't already have a PR open. And if you really want to test a branch outside of a PR, you could do so in a fork that is set up on travis.

**Comment by davidxia** [comment]
Ah so "build pushes" build all pushes to all branches? We can't limit it to only master?

**Comment by mattnworb** [comment]
Could probably do that by examining some of the `TRAVIS_` [environment variables](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) in the build script and exiting if it's not a PR and not master, but I'm not sure if that is very useful then if the PR build tests the merge commit anyway

**Comment by mattnworb** [comment]
also sorry @johnflavin for hijacking the comments in this PR :smile:

**Comment by mattnworb** [comment]
:+1: to the actual change in this PR. I think `List<Object>` is fine if the return value from the API is so ambiguous/poorly documented. Could also do something even more abstract like `List<JsonNode>` or some other Jackson type; I think both are fine.

**Comment by johnflavin** [comment]
Anything else needed to merge this one, @davidxia & @mattnworb?

**Pull request merged**
