### PR TITLE
add support for http cookies

### PR DESCRIPTION
**Pull request by sayarg**
i had to do a bit of a refactor to allow me to test for backwards compatibility for when no cookies are provided as well as with the new functionality.

addressing issue https://github.com/spotify/docker-client/issues/342

### CODE REVIEW

**Comment by sayarg** [comment]
@mattnworb @davidxia 

hey guys, any objections to add this cookie support?

**Comment by davidxia** [comment]
What kind of cookies do you need to send to the docker daemon? Just curious.

**Comment by sayarg** [comment]
@davidxia yes that sounds awkward. The cookies are for an nginx proxy I front the daemon with. The cookie usage ends there. I don't even know if the daemon takes any cookies.

**Comment by davidxia** [comment]
Arbitrary header support might be the way to go in this case. Users can then set cookies in the headers.

**Comment by sayarg** [comment]
@davidxia yes agreed. i'll add headers then and post.

**Pull request closed without merging**
