### PR TITLE
add support for restart policy

### PR DESCRIPTION
**Pull request by sayarg**
Add restart policy support in host config. for issue: https://github.com/spotify/docker-client/issues/168

### CODE REVIEW

**Comment by mattnworb** [comment]
:+1: nice job on the tests

**Comment by sayarg** [comment]
thanks. unfortunately i do not have access to the public registry locally so was not able to run the integration tests hence the first failure.

are you ok to merge this PR to master please?

**Comment by davidxia** [comment]
@sayarg Great. Thanks for the PR!

**Comment by sayarg** [comment]
thanks for merging! looking forward to using it.

now let's talk about releases :-). how are you managing schedules? when do you think you'd be able to do one?

**Comment by davidxia** [comment]
@sayarg Just did one. We usually do one every few commits or so.

**Comment by sayarg** [comment]
great tvm!

**Pull request merged**
