### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by davidxia**
Also update deprecated code and fix some checkstyle errors

### CODE REVIEW

**Comment by davidxia** [comment]
@mattnworb

**Comment by mattnworb** [comment]
jinx https://github.com/spotify/docker-client/commit/3d7ba161ec637e365f8bad4aa2dea76ea164dbac

**Comment by mattnworb** [comment]
:+1: 

I think these checkstyle rules that are currently set to warnings, e.g.

```xml
<module name="LeftCurly">
      <!-- Checks for placement of the left curly brace ('{'). -->
      <property name="severity" value="warning"/>
</module>
```

should have the warning part removed, otherwise contributors will probably keep committing violations

**Comment by davidxia** [comment]
@mattnworb Ha I didn't realize you also had one. Want to take this PR one since it has extra stuff?

Do you mean we should set the checkstyle severity to error?

**Comment by mattnworb** [comment]
> Do you mean we should set the checkstyle severity to error? If so, just that one or more?

Yes, sorry for not being clear. I think if those whitespace-type rules are only severity warning then they would be constantly ignored. I'll add a PR for changing that.

**Comment by davidxia** [comment]
cool, I'll merge this then

**Pull request merged**
