### PR TITLE
Support more exec create params

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by davidxia** [comment]
will try to write some tests once docker hub is fixed.

**Comment by davidxia** [comment]
todo: update `ExecState` accordingly and write tests https://docs.docker.com/engine/reference/api/docker_remote_api_v1.18/#exec-inspect

**Comment by davidxia** [comment]
@mattnworb

**Comment by davidxia** [comment]
@rohansingh

**Comment by mattnworb** [comment]
LGTM.

From a design perspective it seems like a headache that so many lines of code are needed just to add new params, but I guess that is the cost of this fluent style of API

**Comment by davidxia** [comment]
Yea it's a lot of boilerplate, but hopefully it makes it more discoverable and structured for the user.

**Pull request merged**
