### PR TITLE
Add RootFS property to InspectImage response

### PR DESCRIPTION
**Pull request by BastianVoigt**

### CODE REVIEW

**Comment by BastianVoigt** [comment]
Not sure, probably it was added somewhere around docker version 1.10 when they changed the way images and layers are stored on disk

**Comment by BastianVoigt** [comment]
So I finally figured out how to solve the license issue. Two spaces were missing at the end of the line :-(.

**Comment by mattnworb** [comment]
@BastianVoigt  sorry for the headache about the license headers, you can also just run `mvn license:update-file-header` to have the same plugin automatically update files.

As for the failing test, I think it was just a flaky integration test, I re-ran it and it passed.

**Comment by mattnworb** [comment]
thanks again for the PR!

**Comment by BastianVoigt** [comment]
What do you think when it can be released?

**Comment by BastianVoigt** [comment]
@mattnworb do you think you can release this anytime soon? Or should I build my own release from the fork. Bcs I need to use this feature in my project. Thanks!

**Comment by mattnworb** [comment]
I'll kick off a release today

**Comment by mattnworb** [comment]
8.8.2 should be on it's way to Maven central now

**Pull request merged**
