### PR TITLE
maven-compiler-plugin 3.7.0

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
@davidxia  the Travis build failed, but I don't think the failures are related to my change.

**Comment by davidxia** [comment]
@sullis Thanks for your PR. Just curious what you need from the upgrade. If you rebase on master, tests should pass.

**Comment by mattnworb** [comment]
@sullis can you mention something about why this is upgraded?

**Comment by sullis** [comment]
obsolete.

**Pull request closed without merging**
