### PR TITLE
Added load/save support (second attempt)

### PR DESCRIPTION
**Pull request by yduchesne**
Hi guys, me again. I think I've reach the limits of my Git skills (still need honing those).  Thought I'd do better than my previous attempt (see: https://github.com/spotify/docker-client/pull/298) but could not get  the squashing right.

Aside from the squashing issue, I've factored in all comments. Here's a reminder of what the contribution is about:

- DockerClient.load allows loading the tarball of an image as a stream. An image name must be passed in, and the load implementation internally tags the just loaded image with the provided name. The load implementation is passed on Docker API's pull, which takes a fromSrc parameter, indicating it to treat the request's body as the .tar payload of the image.

- DockerClient.save allows pulling the .tar stream of an image (and saving it locally or whatever).

You'd be very kind to accept this contribution and rest assured I'll try to polish my Git skills for next time (I look forward to using your client in a current project, and would not hesitate contributing to it again).

### CODE REVIEW

**Comment by yduchesne** [comment]
BTW, one thing I don't get is that I dont see the "Fixed CircleCI" in my commits in my branch after my rebasing/squashing attempt. Yet it sill appears above. Not sure where that's taken from.

**Comment by mattnworb** [comment]
@yduchesne sounds like maybe you rebased/squashed locally but didn't push the updated branch to your fork? You would need to do `git push -f` to update it

**Comment by yduchesne** [comment]
That's the point, I did... So I'm not sure how the history above is "composed". It does not seem like an actual representation of the git repo's history. Strange.

**Comment by davidxia** [comment]
@yduchesne It was a bit tricky, but I've opened a new PR here https://github.com/spotify/docker-client/pull/301 with all the commits squashed.

**Pull request closed without merging**
