### PR TITLE
Add support for credsStore in new docker versions

### PR DESCRIPTION
**Pull request by smythie86**
This is a fix for this issue: https://github.com/spotify/docker-client/issues/657

### CODE REVIEW

**Comment by gavinbunney** [comment]
Any update on this being merged in? `credsStore` support would be 💯

**Comment by smythie86** [comment]
As far as I know, I am still waiting for this to be reviewed.

**Comment by ssozonoff** [comment]
It would be amazing if this could get pushed through ....

**Comment by lhanson** [comment]
Is there anything else that can be done to get this reviewed? This would unblock a lot of peoples' workflows.

**Comment by mattnworb** [comment]
version 8.11.2 should be on the way to maven central now

**Comment by yuelipku** [comment]
Does it mean we could now use `dockerfile-maven` plugin with `credHelpers`?
I used the aws ecr credential helper but the dockerfile-maven could not recognize that.

**Pull request merged**
