### PR TITLE
add a note on Docker for Mac

### PR DESCRIPTION
**Pull request by mattnworb**
the DOCKER_HOST value might not be obvious.

### CODE REVIEW

**Comment by mattnworb** [comment]
@spotify/helios-team

**Comment by johnflavin** [comment]
Might it be better to change `DefaultDockerClient.defaultEndpoint()` so that it will use `unix:///var/run/docker.sock` for both linux and OS X? Then users with Docker for Mac would not have to set `DOCKER_HOST` at all.

**Comment by mattnworb** [comment]
@johnflavin fair point. I also wanted to document what value to use for people using older docker-client versions as well, prior to any logic that might get added.

**Comment by davidxia** [comment]
👍

**Pull request merged**
