### PR TITLE
Basic support for the network API.

### PR DESCRIPTION
**Pull request by teetrinkers**
Hi, I implemented basic support for the network API introduced in 1.21 / docker 1.9. It doesn't do everything yet, but allows to list, create and remove networks.

### CODE REVIEW

**Comment by teetrinkers** [comment]
The tests are failing because CircleCI is still on docker 1.8. Can you update it?

**Comment by davidxia** [comment]
@teetrinkers Thanks for the PR. Can you use an `assumeTrue` for the version issue? https://github.com/spotify/docker-client/blob/master/src/test/java/com/spotify/docker/client/DefaultDockerClientTest.java#L1198

We're probably not going upgrade our CircleCI setup to docker 1.9 because we're still using the previous docker version for production and we'd like to not deviate too much.

**Comment by davidxia** [comment]
#307 Looks more full featured. Let's replace this with that one?

**Comment by teetrinkers** [comment]
Hi, I just came back from christmas. #307 looks great!

**Pull request closed without merging**
