### PR TITLE
Debug testInspectTask

### LINKED ISSUE #756: start requiring Java 8?
Java 7 has been [EOL since April 2015](http://www.oracle.com/technetwork/java/eol-135779.html). Do we still need to support it in this library, i.e. compile for target=1.7 source=1.7?

The motivation for this question is that I started to use [our hamcrest-jackson](https://github.com/spotify/java-hamcrest) library in some unit tests in #753 but forgot that this library is built with Java 7 and hamcrest-jackson is built with 8.

Is there anyone using this that is stuck on 7 for some reason, or some other argument to be made against moving to compiling with 8?

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by mattnworb** [comment]
this test fails a lot for me in #1068 too.

**Comment by mattnworb** [comment]
is there much of a point to asserting the data that the docker daemon is returning here anyway? I’d rather see a test that checks that the data returned by this call is correct given some mock response from the daemon, but not something that presumes some correctness or behavior inside the daemon.

**Comment by davidxia** [comment]
agreed. I'll replace with a unit test.

**Comment by davidxia** [comment]
replaced by https://github.com/spotify/docker-client/pull/1090

**Pull request closed without merging**
