### PR TITLE
Add operating system to Info message

### PR DESCRIPTION
**Pull request by rohansingh**
You can now do this:

    dockerClient.info().operatingSystem()

### CODE REVIEW

**Comment by davidxia** [comment]
Let's also check this in the test. See https://github.com/spotify/docker-client/pull/135

**Comment by rohansingh** [comment]
So the reason I didn't add a test for it is because this isn't returned until v1.2.

**Comment by davidxia** [comment]
oh in that case :+1: 

On an unrelated note, should we state what versions of docker we actually test against?

**Comment by rohansingh** [comment]
Yeah, we should and I think we should probably increase the minimum Docker version we support (at which point we could add that test). I'm guessing that we'd break against Docker v1.0 in actuality, but we claim to support it.

**Comment by rohansingh** [comment]
By "claim to support it" I mean that the remote API version string makes it seem like we want to talk the Docker 1.0 API, even though we don't.

**Pull request merged**
