### PR TITLE
#446 make default docker client thread safe

### LINKED ISSUE #446: Connection pool is shut down
## Description

Getting `Connection pool is shut down` after some time. Seems to be a Jersey issue.
## How to reproduce

We have a daemon process using the client like that:

```
    private void request() {
         try (DockerClient dockerClient = getDockerClient()) {
         } catch (Exception e) {
             //Log exception
         }
    }

    private static DockerClient getDockerClient() {
        final long TIMEOUT = 5 * 60 * 1000;
        return DefaultDockerClient.builder()
                .uri(URI.create("http://url/"))
                .readTimeoutMillis(TIMEOUT)
                .build();
    }

```
## What do you expect

Client should continue to work.
## What happened instead

Client connection pool is shut  down.
## Software:
- docker version: 1.11
- docker-client version: 3.6.8
## Full backtrace

``` text
com.spotify.docker.client.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.lang.IllegalStateException: Connection pool shut down
        at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:1488)
        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1441)
        at com.spotify.docker.client.DefaultDockerClient.removeContainer(DefaultDockerClient.java:661)
        at <some our classes>
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.lang.IllegalStateException: Connection pool shut down
        at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
        at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:1439)
        ... 11 more
Caused by: javax.ws.rs.ProcessingException: java.lang.IllegalStateException: Connection pool shut down
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
        at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
        at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:177)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
        at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:209)
        ... 5 more
Caused by: java.lang.IllegalStateException: Connection pool shut down
        at org.apache.http.util.Asserts.check(Asserts.java:34)
        at org.apache.http.pool.AbstractConnPool.lease(AbstractConnPool.java:184)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:251)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:175)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
        ... 21 more
```

### PR DESCRIPTION
**Pull request by unicolet**
Fixes #446 

The problem was that `DEFAULT_CONFIG` in `DefaultDockerClient.java` was not thread safe. The rest is just Intellij *optimizations* and a test to verify the fix.

If you merge this **PLEASE** release a new version of maven-docker-client with the fix, which is the only reason for this PR to exist in the first place.

### CODE REVIEW

**Comment by unicolet** [comment]
@mattnworb thank for reaching out, sure I'll fix them. I was not sure what the problem was :smile: 

> 1. do you have any reference to ClientConfig not being thread-safe, or any idea where in it's implementation the unsafeness is coming from?

we use the maven plugin and it only breaks once you reach a certain number of parallel tasks. The problem is not with `ClientConfig` itself which, AFAIK, might be perfectly thread safe, but with the fact that, being static, it is shared across all instances of `DefaultDockerClient` without locking. So it might happen that two clients share the same thread pool. When one finishes it shuts down the pool and the other client gets the exception when it attempts another operation. Try running the test with and without `static` :-)

> 2. any idea if this is related to #727?

sorry, no

**Comment by mattnworb** [comment]
> The problem is not with ClientConfig itself which, AFAIK, might be perfectly thread safe, but with the fact that, being static, it is shared across all instances of DefaultDockerClient without locking. So it might happen that two clients share the same thread pool. 

Is the thread pool owned by the Client or the ClientConfig?

I've found some conflicting information on this:

- http://stackoverflow.com/questions/14305655/jersey-client-services-closing-resources
- [JERSEY-3306 (which is sadly only available in the Google cache since java.net was closed down)](https://webcache.googleusercontent.com/search?q=cache:iDHZniEnM5QJ:https://java.net/jira/browse/JERSEY-3036+&cd=2&hl=en&ct=clnk&gl=us)

**Comment by unicolet** [comment]
@mattnworb sorry I am in a bit of a rush, I wrote thread pool when I meant connection pool.

There is a small window of opportunity between [here](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L414) and [here](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DefaultDockerClient.java#L469). when two instances might share the same connection pool.

I have made some research a couple of weeks ago and then paused it to take care of other stuff so I'm not 100% fresh :-) My research was that all other parts are fine and/or were fixed in earlier releases than those this project uses currently.

**Comment by mattnworb** [comment]
@unicolet good catch - `.property(ApacheClientProperties.CONNECTION_MANAGER, cm)` is mutating the original (shared) CLIENT_CONFIG. Seems like maybe someone may have assumed that those methods were returning new instances and that the config was immutable.

Thanks for clarifying btw - I just wanted to be extra sure that this is actually the problem before we claim to have fixed #446

**Comment by unicolet** [comment]
@mattnworb I need this more than you think :stuck_out_tongue: Please, please, please with :cherries: on top make sure this makes it into maven plugin. Could you look at why the tests fail? I will fix it right away if you could give me a hint :-)

**Comment by mattnworb** [comment]
the two test failures look transient/random to me, but I kicked them off again just to double-check

**Comment by unicolet** [comment]
@mattnworb still failing, I'll take a look tomorrow. Cheers :-)

**Comment by mattnworb** [comment]
after re-running the tests in travis a bunch of times I am convinced the failures are due to flaky tests. Thanks again for the contribution!

**Comment by unicolet** [comment]
@mattnworb thanks, please port this to https://github.com/spotify/docker-maven-plugin :heart:

**Pull request merged**
