### PR TITLE
Update Maven build configuration, dependencies and adapt code to them.

### PR DESCRIPTION
**Pull request by akurtakov**
* Update maven plugin versions.
* Update parent pom.

### CODE REVIEW

**Comment by davidxia** [comment]
@akurtakov Thanks for this!

@rohansingh How does it look to you? Specifically this part https://github.com/spotify/docker-client/pull/222/files#diff-a479355e73762bc07b466a285d105088R273. Did we not need to do this before?

**Comment by rgrunber** [comment]
I was just looking at @akurtakov's patch and noticed the SO_LINGER changes so I thought I'd clarify. As of Apache HttpCore 4.4.0, setSoLinger is now being used in BHttpConnectionBase (See apache/httpcore@c166b587fb1861b46634b2697450fc6bda979bd8 ). Going from 4.3.5 to 4.5.0 would probably cause users to hit this as it happened with Issue #146.

**Comment by davidxia** [comment]
@rgrunber Ah thanks for explaining. I'll wait for another :+1: from either @rohansingh or @gimaker

**Comment by maxandersen** [comment]
any update on this ?

**Pull request merged**
