### PR TITLE
Provides basic filtering of container list by labels

### PR DESCRIPTION
**Pull request by itzg**
...and also populates the `Node` field of the `ContainerInfo` when accessing a Swarm cluster.

### CODE REVIEW

**Comment by itzg** [comment]
It doesn't look like the test failure is related to my changes:

```
- testConnectionRequestTimeout
Dec 22, 2015 5:44:16 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (org.apache.http.NoHttpResponseException) caught when processing request to {}->http://127.0.0.1:2375: The target server failed to respond
Dec 22, 2015 5:44:16 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:2375
```

**Comment by davidxia** [comment]
@itzg Thanks for the PR. I have a similar PR here https://github.com/spotify/docker-client/pull/313. Do you mind rebasing yours on top of mine once it's merged?

**Comment by itzg** [comment]
Excellent. I'd be glad to.

**Comment by davidxia** [comment]
BTW, the tests should be fixed as well once you rebase.

**Comment by davidxia** [comment]
Thanks. You can rebase now.

**Pull request closed without merging**
