### PR TITLE
ISSUE-778: Quick fix for path matching error

### PR DESCRIPTION
**Pull request by ssullivan**
I've been running into the issue reported in ISSUE #778 and this is what I've been using as a quick fix  for the problem (it may not be the best way to do it but thought I would share)

### CODE REVIEW

**Comment by lucastheisen** [comment]
This is the patch I was gonna suggest:
```
$ git diff
diff --git a/src/main/java/com/spotify/docker/client/CompressedDirectory.java b/src/main/java/com/spotify/docker/client/CompressedDirectory.java
index 70d22a9..54f65ce 100644
--- a/src/main/java/com/spotify/docker/client/CompressedDirectory.java
+++ b/src/main/java/com/spotify/docker/client/CompressedDirectory.java
@@ -24,9 +24,6 @@ import static com.google.common.base.Strings.isNullOrEmpty;
 import static org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.BIGNUMBER_POSIX;
 import static org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.LONGFILE_POSIX;

-import com.google.common.annotations.VisibleForTesting;
-import com.google.common.collect.ImmutableList;
-
 import java.io.Closeable;
 import java.io.IOException;
 import java.io.OutputStream;
@@ -36,6 +33,7 @@ import java.nio.file.FileSystems;
 import java.nio.file.FileVisitOption;
 import java.nio.file.FileVisitResult;
 import java.nio.file.Files;
+import java.nio.file.InvalidPathException;
 import java.nio.file.Path;
 import java.nio.file.PathMatcher;
 import java.nio.file.SimpleFileVisitor;
@@ -53,6 +51,9 @@ import org.apache.commons.compress.compressors.gzip.GzipCompressorOutputStream;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;

+import com.google.common.annotations.VisibleForTesting;
+import com.google.common.collect.ImmutableList;
+
 /**
  * This helper class is used during the docker build command to create a gzip tarball of a directory
  * containing a Dockerfile.
@@ -424,7 +425,13 @@ class CompressedDirectory implements Closeable {
      */
     @Override
     public boolean matches(Path path) {
-      return path.startsWith(this.pattern) || this.matcher.matches(path);
+      boolean startsWith = false;
+      try {
+        startsWith = path.startsWith(this.pattern);
+      } catch (InvalidPathException e) {
+        // thrown "If the path string cannot be converted to a Path"
+      }
+      return startsWith || this.matcher.matches(path);
     }

     @Override
```

**Comment by davidxia** [comment]
This PR seems to err on the side of ignoring things. @ssullivan does your patch work on your [`.dockerignore`](https://gitlab.com/pastdev/docker-foo-service/blob/spotifypluginfail/.dockerignore). Does it ignore everything except `target/docker-foo-service.war`?

**Comment by lucastheisen** [comment]
I just attempted another build after applying my suggested patch, and run into more issues having to do with Illegal characters in paths...  I will update my suggestion and post a pull request...

```
Tests in error:
  testCreateServiceWithSecretHostnameHostsAndHealthcheck(com.spotify.docker.client.DefaultDockerClientTest): Request error: POST http://localhost:2375/services/create:
 500, body: {"message":"rpc error: code = 3 desc = ContainerSpec: Interval in HealthConfig cannot be less than 1ms"}(..)
  testSsl(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-classes/dockerSslDi
rectory
  testNetworksConnectContainerWithEndpointConfig(com.spotify.docker.client.DefaultDockerClientTest): Request error: POST http://localhost:2375/networks/create: 409, bo
dy: {"message":"cannot create network 1b29e6f2ad71bd00136d8350dd5183ab645eceea7388f16b8602f04914ea1247 (br-1b29e6f2ad71): conflicts with network 1a5f41a14aa1fedbde6b14
dc206f4ae84019566e9adea35f7fb9c8d3bb9cb85d (br-1a5f41a14aa1): networks have overlapping IPv4"}(..)
  testFailedBuildDoesNotLeakConn(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/t
est-classes/dockerDirectoryNonExistentImage
  testBuildName(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-classes/docke
rDirectory
  testBuildNoRm(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-classes/docke
rDirectory
  testBuildNoTimeout(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-classes/
dockerDirectorySleeping
  testStorageOpt(com.spotify.docker.client.DefaultDockerClientTest): Request error: POST http://localhost:2375/containers/create?name=b3ec85b34871a53b-8c35f29f5224e9ee
: 500, body: {"message":"--storage-opt is supported only for overlay over xfs with 'pquota' mount option"}(..)
  testBuildWithPull(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-classes/d
ockerDirectory
  testBuildImageIdWithBuildargs(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/te
st-classes/dockerDirectoryWithBuildargs
  testBuildImageIdPathToDockerFile(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target
/test-classes/dockerDirectory
  testBuildImageId(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-classes/do
ckerDirectory
  testHealthCheck(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-classes/doc
kerDirectoryWithHealthCheck
  testBuildNoCache(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-classes/do
ckerDirectory
  testBuildImageIdWithAuth(com.spotify.docker.client.DefaultDockerClientTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-cl
asses/dockerDirectory
  testDockerCertificatesWithMultiCa(com.spotify.docker.client.DockerCertificatesTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target
/test-classes/dockerSslDirectory
  testReadPrivateKeyPkcs1(com.spotify.docker.client.DockerCertificatesTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-clas
ses/dockerSslDirectory
  testReadPrivateKeyPkcs8(com.spotify.docker.client.DockerCertificatesTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/test-clas
ses/dockerSslDirectory
  testBadDockerCertificates(com.spotify.docker.client.DockerCertificatesTest): Unexpected exception, expected<com.spotify.docker.client.exceptions.DockerCertificateExc
eption> but was<java.nio.file.InvalidPathException>
  testDefaultDockerCertificates(com.spotify.docker.client.DockerCertificatesTest): Illegal char <:> at index 2: /C:/Users/ltheisen/git/spotify-docker-client/target/tes
t-classes/dockerSslDirectory

Tests run: 289, Failures: 7, Errors: 20, Skipped: 4
```

**Comment by lucastheisen** [comment]
Looks like the `Illegal char <:>` issue has to do with [non-standard uri's](https://stackoverflow.com/a/17870390/516433).  Specifically:

> File.toURI() is worse than Path.toUri() because File.toURI() returns an unusual non-RFC 1738 URI (gives **file:/ instead of file:///**) and does not format URIs for UNC paths according to Microsoft’s preferred format. None of these UNC URIs work in Firefox though (Firefox requires file://///).

Which `Resource.getResources` (which in turn calls `ClassLoader.getResource`) appears to suffer from the same problem.  Switching from:

```
    final String dockerDirectory =
        Resources.getResource("dockerSslDirectory").getPath();
```

to:

```
    final String dockerDirectory = Paths.get(
        Resources.getResource("dockerSslDirectory").toURI()).toString();
```

will resolve this issue.

**Comment by mattnworb** [comment]
regarding `DockerIgnorePathMatcher.matches()`, maybe the simpler change is to add a windows-specific check to `match()` that doesn't call `path.startsWith(this.pattern)` if `this.pattern.contains("*")`? 

Would prefer to check the OS and/or it's limitations rather than calling `path.startsWith(this.pattern)` and _assuming_ a `InvalidPathException` is only thrown because the pattern contained `*` and the code was running on Windows - in other words, ignore the InvalidPathException might be too broad.

**Comment by lucastheisen** [comment]
@mattnworb , I didn't dig too deep, but was under the impression that the `path.startsWith(this.pattern)` check was a short circuit to avoid the more costly `DockerIgnorePathMatcher.matches()`.  In any case, other issues can cause the `InvalidPathException` to be thrown as I discovered when using your unit tests.  I had to update them because java's `URL.getPath()` returns an _[invalid file path](https://github.com/spotify/docker-client/pull/779#issuecomment-306052712)_ which in turn was causing this exception because you were converting it to a `Path` (transitively).  You can see my suggested fix for those issues as well on [my pull request](https://github.com/spotify/docker-client/pull/780/files)...  But I could be missing something.

**Comment by davidxia** [comment]
closed in favor of #779

**Pull request closed without merging**
