### PR TITLE
Add support for missing parameter for execCreate 

### PR DESCRIPTION
**Pull request by zzzsfk**
execCreate parameter "user" is missing so default docker exec's commands files owns root. Added user query param to exeCreate.

### CODE REVIEW

**Comment by davidxia** [comment]
@zzzsfk Thanks for this. How come the user field isn't documented here? http://docs.docker.com/engine/reference/api/docker_remote_api_v1.18/#exec-create

Also, you should convert ExecParameter to an inner class named ExecParam and add the user field to that similar to the design of LogsParam.

**Comment by mattnworb** [comment]
If I understand the docker source correctly, [the JSON in the body is decoded](https://github.com/docker/docker/blob/v1.8.0/api/server/server.go#L1450) into an [ExecConfig struct](https://github.com/docker/docker/blob/v1.8.0/runconfig/exec.go#L8) so `User` definitely looks supported.

**Comment by davidxia** [comment]
Ah I see, thanks. Docker docs :(

**Comment by davidxia** [comment]
To be replaced by https://github.com/spotify/docker-client/pull/316

**Pull request closed without merging**
