### PR TITLE
Swarm Mode Operations (init, join, leave, update, unlockkey, unlock)

### PR DESCRIPTION
**Pull request by tiagoalves83**
For testing purpose:
```
// Creating Docker Vm's
docker-machine create -d virtualbox t1
docker-machine create -d virtualbox t2
```

```
// Disabling TLS for t1 and t2
docker-machine ssh t1 | t2 
# sudo su -
# vi /var/lib/boot2docker/profile
DOCKER_HOST='-H tcp://0.0.0.0:2375'
DOCKER_TLS=no
# source /var/lib/boot2docker/profile
# /etc/init.d/docker stop
# /etc/init.d/docker start
# exit
$ exit
```

I have tested "init", "join", "leave" and "inspect" with the following java code:
```
private static final Logger LOGGER = Logger.getAnonymousLogger();

public static void main(String[] args) throws Exception {

    DockerClient client1 = DefaultDockerClient.builder()
        .uri("http://192.168.99.100:2375")
        .build();
    LOGGER.info("Client 1: OK");

    SwarmInit swarmInit = SwarmInit.builder()
        .forceNewCluster(false)
        .advertiseAddr("192.168.99.100:2377")
        .listenAddr("0.0.0.0:2377")
        .build();

    client1.initSwarm(swarmInit);
    LOGGER.info("initSwarm(): OK");

    Swarm swarm = client1.inspectSwarm();
    LOGGER.info("inspectSwarm(): OK");

    String token = swarm.joinTokens().worker();
    
    DockerClient client2 = DefaultDockerClient.builder()
        .uri("http://192.168.99.101:2375")
        .build();
    LOGGER.info("Client 2: OK");
    
    List<String> remoteAddrs = new ArrayList<>();
    remoteAddrs.add("192.168.99.100:2377");
    
    SwarmJoin swarmJoin = SwarmJoin.builder()
        .advertiseAddr("192.168.99.101:2377")
        .listenAddr("0.0.0.0:2377")
        .joinToken(token)
        .remoteAddrs(remoteAddrs)
        .build();
    
    client2.joinSwarm(swarmJoin);
    LOGGER.info("joinSwarm() OK");
    
    client2.leaveSwarm();
    LOGGER.info("leaveSwarm() OK");
    
    client1.leaveSwarm(true);
    LOGGER.info("leaveSwarm(true) OK");
    
    client1.close();
    client2.close();
    LOGGER.info("Finished!");
  }
```

And everything works fine.

### CODE REVIEW

**Comment by johnflavin** [comment]
This is hard to review because you changed so much whitespace. Can you change all that back? You may have to adjust the settings in your IDE.

**Comment by tiagoalves83** [comment]
@johnflavin Sure. 
How can I make it pass in travis-ci checks ?

**Comment by mattnworb** [comment]
@tiagoalves83 seems like Travis fail because of the checkstyle violations, so addressing those first would allow for the build to get further along to actually testing the change.

**Comment by johnflavin** [comment]
You may find it helpful to run checkstyle locally before pushing your changes. That will give you feedback much faster than waiting for travis to build the project. I believe you can run the task as  `mvn checkstyle:check`.

**Comment by tiagoalves83** [comment]
@johnflavin mvn checkstyle:check OK. But spaces still the same. Sorry. I has been a long time that I don't code in Java / eclipse.

If it helps, my changes are just from lines 1688 to 1844 in src/main/java/com/spotify/docker/client/DefaultDockerClient.java the other classes ares brand new.

```
[INFO] ------------------------------------------------------------------------
[INFO] Building docker-client 8.3.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.17:check (default-cli) @ docker-client ---
[INFO] Starting audit...
Audit done.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.827 s
[INFO] Finished at: 2017-05-01T23:03:52-03:00
[INFO] Final Memory: 20M/394M
[INFO] ------------------------------------------------------------------------
```

**Comment by tiagoalves83** [comment]
@johnflavin travis is failing with a lot of "JavadocMethod: Unable to get class information for @throws tag ..." errors ... No checkstyle erros were found.

**Comment by tiagoalves83** [comment]
@johnflavin How does it look now ?

**Comment by davidxia** [comment]
@tiagoalves83 I started another PR for this that also includes tests. https://github.com/spotify/docker-client/pull/729. Do you mind if we use that one?

**Comment by tiagoalves83** [comment]
@davidxia Not a problem, you can close this if you want. I made another PR related to Swarm https://github.com/spotify/docker-client/pull/733. It is an addition to "/info" API.

**Comment by davidxia** [comment]
Thanks, sorry for not telling you explicitly early and causing some duplicate work.

**Pull request closed without merging**
