### PR TITLE
Make unauthed image pull error clearer

### PR DESCRIPTION
**Pull request by davidxia**
Updated corresponding test

### CODE REVIEW

**Comment by mattnworb** [comment]
does the Remote API actually return 401? I don't see it [in the docs](https://docs.docker.com/engine/api/v1.28/#operation/ImageCreate)

**Comment by davidxia** [comment]
A 401 is returned (at least on recent versions of docker). It's not in the docs. I opened a PR upstream to update docs. https://github.com/moby/moby/pull/33499

**Comment by mattnworb** [comment]
I have some work in 775 and 777 that would be nice to release with this.

**Comment by davidxia** [comment]
Oops, the 401 I saw was coming from the docker registry.

**Pull request closed without merging**
