### PR TITLE
Add (documented) info fields

### PR DESCRIPTION
**Pull request by johnflavin**
The `/info` API has seen a lot of changes in recent versions, which I've attempted to capture.

# Changes
* Add many new properties to `Info` class.
* Alphabetize properties in `Info`. There were getting to be too many properties to easily compare to the API docs (in which the example info object is alphabetized).
* Add `Plugin`, `RegistryConfig`, and `IndexConfig` classes to represent some `Info` fields.
* Add tests for all `Info` fields, with fields added in each successive new API version in a new `if` block.

# Caveats
* In my testing I found some undocumented fields returned by `/info`, and I chose not to include them here. I may open an upstream issue about it.
* Most of the test assertions I added don't actually test anything, they just compare to `Matchers.anything()`. I don't have a good way to predict beforehand what most of the fields will be, or even whether they will be null or blank.

### CODE REVIEW

**Comment by johnflavin** [comment]
@mattnworb What's wrong with the codecov reports? I guess they changed how their plugin works, and something is breaking right now.

**Comment by mattnworb** [comment]
@johnflavin not sure. The link in the travis output loads fine: https://codecov.io/github/spotify/docker-client/commit/ea77379f3d1f133b095317c7dc357ddf85c6ebea

**Comment by johnflavin** [comment]
Anyone up for a review?
👉 Poke @mattnworb @davidxia

**Comment by mattnworb** [comment]
LGTM. Sorry for delay, was away for a few weeks.

**Pull request merged**
