### PR TITLE
Updated ContainerConfig for API 1.21 and added imageid to Container

### PR DESCRIPTION
**Pull request by MarcoLotz**
Added fields to container inspection in order to match Docker API 1.21
Added imageid to Container, in order to match the docker API 1.21

No removals. Should work properly with previous docker versions.

https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/

### CODE REVIEW

**Comment by MarcoLotz** [comment]
testInspectContainerWithSecurityOpt test passes with no errors here. Can the timeout be something related with the testing env there?

**Comment by davidxia** [comment]
@MarcoLotz Tests are sometimes flakey. It passed now though :)

**Comment by davidxia** [comment]
@MarcoLotz Looks great. Do you mind adding some tests for these new properties? See here for an example https://github.com/spotify/docker-client/blob/master/src/test/java/com/spotify/docker/client/DefaultDockerClientTest.java#L1218

**Comment by MarcoLotz** [comment]
Added tests and modified getter syntax to be inspection.mounts() instead of inspection.getMounts() from the autogenerated getter.

**Comment by davidxia** [comment]
@MarcoLotz Thanks for adding the tests. Can you undo the changes in DefaultDockerClientTest that are just formatting changes though? It makes the diff look bigger than it actually is.

**Comment by davidxia** [comment]
And squashing into one commit would be great.

**Comment by MarcoLotz** [comment]
@davidxia  Done :)

**Comment by davidxia** [comment]
Thanks

**Pull request merged**
