### PR TITLE
Fix docker-lab/helios#462 (Authentication against private registry.hub.docker.com repositories)

### PR DESCRIPTION
**Pull request by elifarley**
This change is [Reviewable](https://reviewable.io/reviews/spotify/docker-client/473)

### CODE REVIEW

**Comment by mattnworb** [comment]
@elifarley sorry for the delayed review, but can you provide some more context on what `fix docker-lab/helios#462` means?

**Comment by elifarley** [comment]
Sorry, I should have typed something else:
"Fix spotify/helios#462".

Fixed now.

**Comment by mattnworb** [comment]
👍

**Comment by mattnworb** [comment]
@elifarley thanks!

**Pull request merged**
