### PR TITLE
Replace manual calc of hash code with Objects.hash()

### PR DESCRIPTION
**Pull request by davidxia**

### CODE REVIEW

**Comment by mattnworb** [comment]
:-1: for use of the Guava method. See the javadoc in the class:

```java
* <p><b>Note for Java 7 and later:</b> This method should be treated as
   * deprecated; use {@link java.util.Objects#hash} instead.
```

**Comment by davidxia** [comment]
derp

**Comment by davidxia** [comment]
fixed now

**Comment by mattnworb** [comment]
:+1:

**Pull request merged**
