### PR TITLE
Test on v17.03.0-ce

### PR DESCRIPTION
**Pull request by johnflavin**
Test on latest docker release.

### CODE REVIEW

**Comment by davidxia** [comment]
Perhaps we can just drop testing on 1.8.3 which was released 2015-10-12? My motivation for not testing on too many versions is that travis is really flaky and often fails to pull images or, less frequently, install docker. The fewer versions we test on, the less likely a PR is to fail.

**Comment by johnflavin** [comment]
Makes sense.

**Comment by davidxia** [comment]
Want to rebase on master? I saw a failure that https://github.com/spotify/docker-client/pull/681 fixes.

**Comment by johnflavin** [comment]
This has already been rebased on master with #681. So maybe we do need #666.

**Pull request merged**
