### PR TITLE
docker exec command

### PR DESCRIPTION
**Pull request by relgames**
Implemented exec command introduced in Docker 1.3

### CODE REVIEW

**Comment by rohansingh** [comment]
@relgames I think it's fine to have the test aware of the what execution driver is being used. In fact, it's a good signal for anybody who uses this method that they need to do the same thing and check the exec driver before assuming that exec will work.

**Comment by relgames** [comment]
Added API version and driver checks. API at least 1.15 is required and "native" driver.

**Comment by davidxia** [comment]
@relgames 3 tests failed. The 2 tests that are not testExec will be fixed (hopefully) if you rebase onto the latest master.

**Comment by davidxia** [comment]
@relgames Hmm, maybe skip testExec() if we detect that the host doesn't have the native libcontainer driver? Otherwise the test will [fail here](https://github.com/spotify/docker-client/pull/106/files#diff-8b9a5e049d8e8be5e08ee5cc7526354fR1081).

**Comment by JWGmeligMeyling** [comment]
Isnt it so that Assume statements (as suggested) ignore the test if it fails? (Instead of Asserts)

**Comment by relgames** [comment]
Rebased, changed assertThat into assumeThat.

**Comment by relgames** [comment]
Not sure why it still fails:
````
Tests in error: 
  testContainerWithHostConfig(com.spotify.docker.client.DefaultDockerClientTest): 
Request error: POST unix://localhost:80/v1.12/containers/0480cce9f36ae7279db70c4db014c31c1dd84a1c3c9857b74d277c8940ea71ce/kill: 500
````
But I did not touch that part.

**Comment by relgames** [comment]
Well after minor cosmetic change it is fixed. I guess, something was/is wrong with your CI environment...

**Comment by davidxia** [comment]
:+1: CircleCI fails from time to time...

**Pull request merged**
