### PR TITLE
Support for EC algorithm used in Docker EE client bundles (#887)

### PR DESCRIPTION
**Pull request by chrsoo**
@davidxia - as dicsussed dropping #1007 and creating new PR with cherry pick to better handle merge conflicts. Please review!

### CODE REVIEW

**Comment by chrsoo** [comment]
@davidxia please consider removing the checkstyle check for the ordering of import statements!

As it stands now I have to reverse-engineer, disable default IntelliJ formatting rules and manually re-arrange the import statements.

This is killer for productivity and personally I don't even see the point of having the rules unless they automagically configure Eclipse/IntelliJ as part of the Maven import (assuming this is possibly). 

:-(

Will fix the order import as I really would like to see this PR to go through.

**Comment by davidxia** [comment]
Hey, I’ll be able to review your PR Sunday or Monday. As for checkstyle,
don’t worry about it. If your tests pass, I’ll fix the imports later.
Thanks again for contributing.
-- 
David Xia
Software Engineer
dxia@spotify.com

**Comment by davidxia** [comment]
@chrsoo I added a new commit that fixes checkstyle and the test. PTAL.

**Comment by davidxia** [comment]
replaced by https://github.com/spotify/docker-client/pull/1033

**Pull request closed without merging**
