### PR TITLE
Test on latest docker versions

### PR DESCRIPTION
**Pull request by davidxia**
stop testing on 1.11.2

### CODE REVIEW

**Comment by davidxia** [comment]
just testing don't merge

**Comment by ssullivan** [comment]
I think to install 17.0.6 on ubuntu the package has changed from docker-engine to docker-ce so the install script in .travis.sh may need to be updated.

**Comment by davidxia** [comment]
Thanks. I removed `ENABLE_SWARM`. I just like having `UPLOAD_SONATYPE` on the latest even though it doesn't make a difference. :)

**Comment by davidxia** [comment]
yay, tests pass

**Comment by davidxia** [comment]
bump

**Pull request merged**
