### PR TITLE
Add header support

### PR DESCRIPTION
**Pull request by sayarg**
add support for http headers

### CODE REVIEW

**Comment by mattnworb** [comment]
I think this looks fine. I have a few small suggestions but I don't see them as dealbreakers

- to be able to specify a different way of constructing the ClientBuilder, you could also just have the overloaded constructor take a `Supplier<ClientBuilder>`, so that you don't have to define a new interface just for being visible from tests. I think that would read a little easier.
- in the DefaultDockerClientBuilder, looks like a way to add a bunch of headers at once, e.g. `headers(Map)`, would be useful.

Thanks for the contribution and sorry for the slow reply on #343. This would make #343 obsolete, right?

**Comment by sayarg** [comment]
tvm @mattnworb 

just closed https://github.com/spotify/docker-client/pull/343

if ok with you it would be great if you could release this change? happy to do the clean up follow ups too. There's another change i need to put regarding resource leak in the way certificates are loaded, without it you may run out of fd, i'll try to do all these in this week.

cheers.

**Comment by sayarg** [comment]
thanks for merging @mattnworb 

do you know when the next release is going to be?

**Comment by mattnworb** [comment]
@sayarg should be as soon as possible, the Jenkins we use internally is having issues with one of the tests repeatedly failing, so as soon as I fix that we'll have a new version on the way to maven central. Should be a day or two.

**Comment by davidxia** [comment]
I just released 3.6.2

**Comment by sayarg** [comment]
and events are in too! awesome thanks vm.

**Comment by mattnworb** [comment]
thank you for the contribution @sayarg !

**Pull request merged**
