### PR TITLE
Support pulling images by digest & fix broken tests

### PR DESCRIPTION
**Pull request by gimaker**

### CODE REVIEW

**Comment by gimaker** [comment]
@rohansingh @davidxia

**Comment by gimaker** [comment]
hrrm this works locally for me... will have to dig into why tests are failing still

**Comment by davidxia** [comment]
CircleCI's docker client, which is 1.6.2-circleci as of this writing, doesn't pull from public registry v2. So we can't use image hashes as tags. https://github.com/spotify/docker-client/pull/249/files

**Comment by rohansingh** [comment]
:+1:

**Pull request merged**
